# Generated by Django 3.2.12 on 2022-03-09 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавление')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Заметки')),
                ('subject', models.CharField(max_length=300, verbose_name='Тема')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('send_to', models.ManyToManyField(to='core.CourseRegistrations', verbose_name='Получатели')),
            ],
            options={
                'verbose_name': 'Письма',
                'verbose_name_plural': 'Письма',
            },
        ),
    ]
