# Generated by Django 3.2.12 on 2022-03-17 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220317_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='css_file',
            field=models.FileField(blank=True, null=True, upload_to='css_files/', verbose_name='CSS файл'),
        ),
    ]
