# Generated by Django 3.2.12 on 2022-03-19 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_coursesrelease_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesrelease',
            name='attributes',
            field=models.ManyToManyField(blank=True, to='core.Attributes', verbose_name='атрибуты'),
        ),
    ]
