# Generated by Django 3.2.12 on 2022-03-18 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_coursesrelease_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseregistrations',
            name='personal_info',
            field=models.TextField(blank=True, null=True, verbose_name='Допалнительная информация'),
        ),
    ]
